// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactCRUDSupport_v1.Database;

#nullable disable

namespace ReactCRUDSupport_v1.Migrations.ValuesDb
{
    [DbContext(typeof(ValuesDbContext))]
    [Migration("20260220164629_values db creation-initial")]
    partial class valuesdbcreationinitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactCRUDSupport_v1.Models.Domain.AddDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AddOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaef8e29-64f4-4536-a3a8-943d8b8eab0d"),
                            Value = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
