name : build-yaml-test-pipeline

on :
  push :
    branches:
      - main

  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    
      - name: clone repository
        uses: actions/checkout@v4

      - name: add dotnet
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '10.0.x'
      - name: restore dependencies
        run: dotnet restore

      - name: build project
        run:  dotnet build --configuration Release --no-restore
    
